# Objects and Data Structures Assessment Test                         @manojvn

## Test your knowledge. 

** Answer the following questions **

Write a brief description of all the following Object Types and Data Structures we've learned about:

Numbers: Numbers are of two types int and float.

Strings: It is a sequence of characters.

Lists: A list is a data structure in Python that is a mutable, or changeable, ordered sequence of elements.

Tuples: A tuple is an immutable sequence of Python objects.

Dictionaries: Unordered collection of data values, used to store data values like a map.

## Numbers

Write an equation that uses multiplication, division, an exponent, addition, and subtraction that is equal to 100.25.

Hint: This is just to test your memory of the basic arithmetic commands, work backwards from 100.25

In [4]:
100*10/10+1**2-0.75

100.25

Answer these 3 questions without typing code. Then type code to check your answer.

    What is the value of the expression 4 * (6 + 5)
    
    What is the value of the expression 4 * 6 + 5 
    
    What is the value of the expression 4 + 6 * 5

In [5]:
4*(6+5)

44

In [6]:
4*6+5

29

In [7]:
4+6*5

34

What is the *type* of the result of the expression 3 + 1.5 + 4?<br><br>

In [8]:
type(3+1.5+4)

float

What would you use to find a numberâ€™s square root, as well as its square?

In [10]:
# Square root:
9**0.5

3.0

In [9]:
# Square:
2**2

4

## Strings

Given the string 'hello' give an index command that returns 'e'. Enter your code in the cell below:

In [11]:
s = 'hello'
# Print out 'e' using indexing
s[1]

'e'

Reverse the string 'hello' using slicing:

In [13]:
s ='hello'
# Reverse the string using slicing
s[::-1]

'olleh'

Given the string hello, give two methods of producing the letter 'o' using indexing.

In [17]:
s ='hello'
# Print out the 'o'
# Method 1:
s[4]

'o'

In [18]:
# Method 2:
s[-1]

'o'

## Lists

Build this list [0,0,0] two separate ways.

In [21]:
# Method 1:
list=[0,0,0]
list

[0, 0, 0]

In [23]:
# Method 2:
list=[0,0]
list+[0]

[0, 0, 0]

Reassign 'hello' in this nested list to say 'goodbye' instead:

In [25]:
list3 = [1,2,[3,4,'hello']]

list3[2][2]='goodbye'
list3

[1, 2, [3, 4, 'goodbye']]

Sort the list below:

In [27]:
list4 = [5,3,4,6,1]

list4.sort()
list4

[1, 3, 4, 5, 6]

## Dictionaries

Using keys and indexing, grab the 'hello' from the following dictionaries:

In [28]:
d = {'simple_key':'hello'}
# Grab 'hello'
d['simple_key']

'hello'

In [29]:
d = {'k1':{'k2':'hello'}}
# Grab 'hello'
d['k1']['k2']

'hello'

In [32]:
# Getting a little tricker
d = {'k1':[{'nest_key':['this is deep',['hello']]}]}

#Grab hello
d['k1'][0]['nest_key'][1][0]

'hello'

In [33]:
# This will be hard and annoying!
d = {'k1':[1,2,{'k2':['this is tricky',{'tough':[1,2,['hello']]}]}]}
d['k1'][2]['k2'][1]['tough'][2][0]

'hello'

Can you sort a dictionary? Why or why not?<br><br>

## Tuples

What is the major difference between tuples and lists?<br><br>

Ans:- list are mutable , tuples are immutable

How do you create a tuple?<br><br>

t=( , , )

## Sets

What is unique about a set?<br><br>

Ans:- It can be ordered and can be easily formatable

Use a set to find the unique values of the list below:

In [34]:
list5 = [1,2,2,33,4,4,11,22,3,3,2]
set(list5)

{1, 2, 3, 4, 11, 22, 33}

## Booleans

For the following quiz questions, we will get a preview of comparison operators. In the table below, a=3 and b=4.

<table class="table table-bordered">
<tr>
<th style="width:10%">Operator</th><th style="width:45%">Description</th><th>Example</th>
</tr>
<tr>
<td>==</td>
<td>If the values of two operands are equal, then the condition becomes true.</td>
<td> (a == b) is not true.</td>
</tr>
<tr>
<td>!=</td>
<td>If values of two operands are not equal, then condition becomes true.</td>
<td> (a != b) is true.</td>
</tr>
<tr>
<td>&gt;</td>
<td>If the value of left operand is greater than the value of right operand, then condition becomes true.</td>
<td> (a &gt; b) is not true.</td>
</tr>
<tr>
<td>&lt;</td>
<td>If the value of left operand is less than the value of right operand, then condition becomes true.</td>
<td> (a &lt; b) is true.</td>
</tr>
<tr>
<td>&gt;=</td>
<td>If the value of left operand is greater than or equal to the value of right operand, then condition becomes true.</td>
<td> (a &gt;= b) is not true. </td>
</tr>
<tr>
<td>&lt;=</td>
<td>If the value of left operand is less than or equal to the value of right operand, then condition becomes true.</td>
<td> (a &lt;= b) is true. </td>
</tr>
</table>

What will be the resulting Boolean of the following pieces of code (answer fist then check by typing it in!)

In [36]:
# Answer before running cell
2 > 3

False

In [37]:
# Answer before running cell
3 <= 2

False

In [38]:
# Answer before running cell
3 == 2.0

False

In [39]:
# Answer before running cell
3.0 == 3

True

In [40]:
# Answer before running cell
4**0.5 != 2

False

Final Question: What is the boolean output of the cell block below?

In [41]:
# two nested lists
l_one = [1,2,[3,4]]
l_two = [1,2,{'k1':4}]

# True or False?
l_one[2][0] >= l_two[2]['k1']

False

## Great Job on your first assessment!